name: "Team awesome's approval workflow"
on: pull_request_review

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Give a label
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        ADD_LABEL: "100%"
